steps:

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/be-notes-115", "."]


  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/be-notes-115"]


  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "be-notes-115",
        "--image",
        "gcr.io/$PROJECT_ID/be-notes-115",
        "--set-env-vars=DB_HOST=$_DB_HOST,DB_USERNAME=$_DB_USERNAME,DB_PASSWORD=$_DB_PASSWORD,DB_NAME=$_DB_NAME,ACCESS_TOKEN_SECRET=$_ACCESS_TOKEN_SECRET,REFRESH_TOKEN_SECRET=$_REFRESH_TOKEN_SECRET",
        "--timeout",
        "1000s",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]


options:
  logging: CLOUD_LOGGING_ONLY