### 
POST https://be-notes-115-722144796089.us-central1.run.app/users 
Content-Type: application/json

{
"name": "tes", 
"email": "tes@tes.com", 
"gender": "Laki-laki",
"password": "tes"
}

### 
POST https://be-notes-115-722144796089.us-central1.run.app/login 
Content-Type: application/json

{
"email": "123@123", 
"password": "123"
}

###
DELETE https://backend-722144796089.us-central1.run.app/logout
Cookie: refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InRlcyIsImVtYWlsIjoidGVzQHRlcy5jb20iLCJnZW5kZXIiOiJNYWxlIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0xM1QxNjowNjo0NC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0xN1QwNzo1MDo0NC4wMDBaIiwiaWF0IjoxNzQ3NTQ5OTk1LCJleHAiOjE3NDc2MzYzOTV9.DiMsTGhSIE2I4NL_JA2GA8dnXSsTgL3tFlvKpTmpBmA

###
GET https://backend-722144796089.us-central1.run.app/note
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InRlcyIsImVtYWlsIjoidGVzQHRlcy5jb20iLCJnZW5kZXIiOiJNYWxlIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0xM1QxNjowNjo0NC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0xNlQwNjowNjoyOC4wMDBaIiwiaWF0IjoxNzQ3Mzc1NTk3LCJleHAiOjE3NDczNzU2Mjd9.wOuris7NAZUdQp5IRvl1GktYnTuGXVxkbkADJcY9vd0
